apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: talhac/product-service:latest
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80            # Port exposed by the service
      targetPort: 3002    # Port inside the container
      nodePort: 31002     # Fixed external port on the host machine
